LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := Email
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX :=$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES := Email.apk
LOCAL_CERTIFICATE := PRESIGNED

include $(BUILD_PREBUILT)


